### ISSUE TITLE
Connection using ClassiCube doesn't work (timeout)

### ISSUE THREAD

**Issue by typoworx-de** [PrismarineJS/dazed-sheep#28]
ReadMe of Project claims: ```You can use ClassiCube as a client.```

I've tested this with the web-client pointing to 127.0.0.1:25565 after starting ```node app.js```. The port is present using ```nc -vz 127.0.0.1 25565``` but web-client says:
Failed to connect to 127.0.0.1:25565

Is there some special requirement for web-client of ClassiCube to make it work with dazed-sheep?

**Comment by typoworx-de** [comment]
Okay. I was able to resolve it myself. Obvisously the web-client only can use websocket! So I've simply tested a ws-tcp-bride and voila... it works:

https://github.com/andrewchambers/ws-tcp-bridge
``` 
npm install  ws-tcp-bridge
node_modules/ws-tcp-bridge/ws-tcp-bridge --method=ws2tcp --lport=25666 --rhost=127.0.0.1:25565
```
Optionally it may be a nice feature to have this websocket-bridge implemented in dazed-sheep directly ;-)

**Comment by mhsjlw** [comment]
minecraft-classic-protocol includes support for WebSockets already! You're right in that we'd have to add a configuration option to enable that. PRs welcome.
